## Sleep Hours
- id: Wake_Up
  alias: "Wake Up"
  trigger:
    platform: time
    at: '07:00:00'
    condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      service: homeassistant.turn_off
      entity_id: input_boolean.sleep_hours

- id: Go_To_Sleep
  alias: "Go To Sleep"
  trigger:
    platform: time
    at: '11:00:00'
    condition:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
    action:
      service: homeassistant.turn_on
      entity_id: input_boolean.sleep_hours

- id: Wake_Up_Weekend
  alias: "Wake Up Weekend"
  trigger:
    platform: time
    at: '08:30:00'
    condition:
    - condition: time
      weekday:
        - sat
        - sun
    action:
      service: homeassistant.turn_off
      entity_id: input_boolean.sleep_hours

- id: Go_To_Sleep_Weekend
  alias: "Go To Sleep Weekend"
  trigger:
    platform: time
    at: '00:00:00'
    condition:
    - condition: time
      weekday:
        - fri
        - sat
    action:
      service: homeassistant.turn_on
      entity_id: input_boolean.sleep_hours

## Work Hours
- id: Go_To_Work
  alias: "Go To Work"
  trigger:
    platform: time
    at: '08:30:00'
    condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      service: homeassistant.turn_on
      entity_id: input_boolean.away_hours

- id: Go_Home_From_Work
  alias: "Go Home From Work"
  trigger:
    platform: time
    at: '05:30:00'
    condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      service: homeassistant.turn_on
      entity_id: input_boolean.away_hours

## Let there be light (and darkness)
- id: Turn_Lights_On_When_Awake
  alias: "Turn Lights On When Awake"
  trigger:
    - platform: state
      entity_id: input-boolean.sleep_hours
      to: 'off'
  action:
    entity_id: group.all_lights
    service: light.turn_on

- id: Turn_Lights_Off_When_Asleep
  alias: "Turn Lights Off When Asleep"
  trigger:
    - platform: state
      entity_id: input-boolean.sleep_hours
      to: 'on'
  action:
    entity_id: group.all_lights
    service: light.turn_off

- id: Turn_Lights_On_When_Home
  alias: "Turn Lights On When Home"
  trigger:
    - platform: state
      entity_id: input-boolean.away_hours
      to: 'off'
  action:
    entity_id: group.all_lights
    service: light.turn_on

- id: Turn_Lights_Off_During_Work
  alias: "Turn Lights Off During Work"
  trigger:
    - platform: state
      entity_id: input-boolean.away_hours
      to: 'off'
  condition:
    - entity_id: device_tracker.d4_c9_4b_c8_61_79
      state: away
  action:
      service: light.turn_off
      entity_id: group.all_lights

- id: Turn_Lights_On_During_Work_When_Home
  alias: "Turn Lights On During Work When Home"
  trigger:
    platform: state,
    entity_id: device_tracker.d4_c9_4b_c8_61_79
    state: 'home'
  condition:
    condition: state
    entity_id: input_boolean.away_hours
    state: 'on'
  action:
    service: light.turn_on
    entity_id: group.all_lights

- id: Turn_Lights_Off_During_Work_When_Leaving
  alias: "Turn Lights Off During Work When Leaving"
  trigger:
    - platform: state,
      entity_id: device_tracker.d4_c9_4b_c8_61_79
      state: 'away'
  condition:
    condition: state
    entity_id: input_boolean.away_hours
    state: 'on'
  action:
    service: light.turn_off
    entity_id: group.all_lights
